### ISSUE TITLE
Printouts of certificates in IDEs

### ISSUE THREAD

**Issue by apozas** [ecboghiu/inflation#134]
I like the new string-based names for probabilities and operators, since they bring us closer to a general formulation, beyond the distributions of outputs conditioned on inputs that are used in nonlocality. However, I figured out that when VSCode parses the certificates (for instance, that corresponding to Example 1, it parses everything that comes after an underscore as a subscript (in contrast to LaTeX, which understands that only the first character after the underscore is the subscript).

This is naively easy to solve: just needs to substitute [L731 in InflationProblem](https://github.com/ecboghiu/inflation/blob/56ef3a04d24367db8c92437ee5d018dd1da6b712/inflation/InflationProblem.py#L731)

```python
op_as_str += '_'+str(op["Private Setting"])
```
by
```python
op_as_str += '_{'+str(op["Private Setting"])+'}'
```

But if we do this, [TestResetLP](https://github.com/ecboghiu/inflation/blob/56ef3a04d24367db8c92437ee5d018dd1da6b712/test/test_pipeline.py#L266) fails because it searches for `"P[v_0=0 v_1=0]"`.

Right now, we have to make a choice between having nice IDE formatting and making it easy to the user to call a monomial by its name. Right now the code does the latter at the expense of the former. However, it would be nice (I can do it once I have time) to have the braces in the name, and write a small preprocessing step that adds the corresponding braces to the monomial name.

**Comment by apozas** [comment]
In fact this may be a bit more complicated, since it seems like the subscripts are only used when there are input choices (which makes sense), so one has to be a bit careful.

**Comment by eliewolfe** [comment]
What about `op_as_str += repr('_')+str(op["Private Setting"])`? Does the use of `repr` prevent the VSCode parsing problem? The test continues to pass...

**Comment by eliewolfe** [comment]
OK, I think I fixed it now!
I changed the code so that it does some rewriting of the string (using regular expressions) just before SymPy symbol creation.

**Comment by apozas** [comment]
I confirm that it's working. And the fix is so elegant, thanks a lot!
