### ISSUE TITLE
Add ability to evaluate certificates

### ISSUE THREAD

**Issue by ecboghiu** [ecboghiu/inflation#81]
Inspired by https://github.com/ecboghiu/inflation/commit/4a685be53f24bcb69a02ad05b999bbbbffce8916#commitcomment-85905628 it would be nice to add the ability to evaluate the certificate on a probability distribution. This can be easily done with the current functions. One can sanitise the symbolic certificate as it is done with the objective and then evaluate the monomials with known values as is done in `set_values.`

**Comment by apozas** [comment]
Implemented in #128
