### ISSUE TITLE
Detection of Zero monomials relies on an implicit assumption about the lexicographic order

### ISSUE THREAD

**Issue by eliewolfe** [ecboghiu/inflation#96]
The function `mon_is_zero` in fast_npa.py checks if adjacent operators in a sequence agree on everything except for the outcome. This works fine if it is always the case that operators which differ by outcome are adjacent in the lexicographic order. With a nonstandard lexicographic order, however, they might be _separated_ by a third operator which commutes with them both. This is a zero monomial --- because there is way to get the orthogonal operators to become adjacent under commutation, albeit using an ordering inconsistent with the (nonstandard) lexicographic ordering.

I propose that, for now, we add an assertion to the custom lexicographic order to make sure that operators which differ by outcome only are always adjacent. (Longer term we might rewrite `mon_is_zero` to detect orthogonal operators with _any_ sequence of operators between them, and then check if everything in that sequence commutes with the two orthogonal operators of interest.)

**Comment by eliewolfe** [comment]
We have decided to remove non-default lex_orders. This just means skipping the _default_lexorder attribute creation, and instead just creating _lexorder.

**Comment by apozas** [comment]
It seems like this has been addressed by the refactoring that happened when writing the LP part. Please reopen if it is not the case.
